apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: LogFileGeneratorKubeCluster
  region: us-east-2

vpc:
  id: vpc-b55932de
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-2a:
        id: subnet-5155c63a
      us-east-2b:
        id: subnet-6438f119
      us-east-2c:
        id: subnet-b56c5cf9

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
