apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-monitor-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: redis-monitor
          image: 824124316412.dkr.ecr.us-east-2.amazonaws.com/redis_monitor:latest
